#+SETUPFILE: ../theme-rose.setup
#+DATE: <2020-09-03 Thu 17:50>
#+TITLE: 第一卷 物质世界及其发展规律

*马克思主义哲学是唯物主义和辩证法的统一。*

马克思主义的唯物主义认为，世界在本质上的物质的，人与世界关系的基础是实践，人生活于其中的世界是与人的实践相联系的统一的物质世界。

马克思主义的唯物辩证法认为，物质世界是普遍联系和永恒发展的。联系的观点和发展的观点是唯物辩证法的总特征。唯物辩证法是关于自然、社会和思维联系与发展一般规律的科学。

马克思主义哲学揭示了世界的本质和发展的基本规律，为我们正确地发挥主观能动性，即正确地认识世界和改造世界提供了科学的世界观和方法论指导。

** 物质世界和实践

#+BEGIN_QUOTE
社会生活在本质上是实践的。 -- 马克思
#+END_QUOTE

*** 物质世界的客观存在

**** 世界是统一的物质世界

_1. 世界的本质问题是哲学必须回答的重大问题_

*哲学是世界观的理论体系。*

所谓 _世界观_ ，就是人们对包括自然、社会和人类思维在内的整个世界的根本看法和根本观点。

由于人们总是从自身的存在和发展这个基本点出发去认识世界，形成对世界的根本看法和观点，因此，世界观也是人们对人和世界关系的总体把握。

人们在日常生活中形成的世界观是自发的、不系统的。哲学是系统化、理论化的世界观，它从人和世界关系的角度揭示自然、社会和人类思维最普遍的本质和发展的最一般规律。

*哲学是世界观、方法论和价值观的统一。*

 哲学是关于世界观的理论，用这种理论观点去观察、分析和解决问题，就是方法。所以哲学还为人们提供认识世界和改造世界的普遍方法。

哲学既是理论化的世界观，又是方法论。哲学并不只是简单地描述现实世界，而且还批判现实世界，构想更理想的世界。哲学往往作为理想、信念从而也作为价值观对人们起着导向和激励作用。

世界观、方法论与价值观的统一，使哲学与人们的生活息息相关。

*思维和存在或意识和物质的关系问题是哲学的基本问题。*

#+BEGIN_QUOTE
全部哲学，特别是近代哲学的重大的基本问题，是思维和存在的关系问题。

-- 恩格斯
#+END_QUOTE

要回答世界的本质问题，就必须说明思维和存在或意识和物质的关系。因为处人类产生之后，纷繁复杂的万物，归结起来无非就是两大类：一类是物质现象，一类是意识现象。

哲学的基本问题包括两个方面的内容。

第一方面是物质和意识哪个是本原、哪个是第一性的问题。这在哲学上属于本体论的问题，是最重要的方面。如何回答这个问题是划分唯物主义和唯心主义的标准。凡是认为物质是本原的、第一性的，意识是派生的、第二性的哲学，属于唯物主义；凡是认为意识是本原的、第一性的，物质是派生的、第二性的哲学，属于唯心主义。

第二方面是思维和存在的同一性问题，主要指思维能否认识存在的问题，即世界可不可以认识的问题。这在哲学上属于认识论的问题，对这个问题的不同回答，区分为可知论与不可知论。承认思维与存在的同一性，认为世界是可以认识的，属于可知论；否认思维与存在的同一性，认为世界是不可能认识的，属于不可知论。

与哲学基本问题相一致， *社会存在与社会意识的关系问题是社会历史观的基本问题* 。

如何回答社会存在和社会意识哪个是第一性的问题，是划分历史唯物主义和历史唯心主义的标准。凡是认为社会存在决定社会意识的，是历史唯物主义；凡是认为社会意识决定社会存在的，是历史唯心主义。

*物质和意识的关系问题主要是回答世界的本质是什么以及世界可不可以认识的问题。* 它是哲学的基本问题，但不是哲学要研究的全部问题。与这一问题相联系，还有 *世界如何存在的问题* 。即世界上的万事万物是以联系、发展的状态存在，还是以孤立、静止的状态存在的问题。

对于世界如何存在这个问题的不同回答，区分为辩证法和形而上学。

辩证法认为，世界上的事物都是相互联系的、运动发展的，发展的根本原因在于事物的内部矛盾。形而上学则认为，世界上的事物都是彼此孤立的、静止不变的，否认事物内部矛盾的存在。

在哲学上，在唯物主义和唯心主义的对立中，又交织着辩证法和形而上学的对立。

辩证法和形而上学的对立从属于唯物主义和唯心主义的对立，辩证法或形而上学不是同唯物主义相结合，就是同唯心主义相结合。是辩证地还是形而上学地看世界，无论对唯物主义还是唯心主义都有重要的影响作用。

_2. 在世界的本质问题上一元论和二元论、唯物主义和唯心主义的对立_

世界的本质问题，实质上是世界的统一性问题。

世界上纷繁复杂、多种多样的万事万物有没有统一性，即有没有一个共同的本质或本原？如果有，世界统一性的基础是什么，即这个共同的本质或本原是什么？

这就是世界的统一性问题。对这个问题的回答存在着一元论和二元论、唯物主义和唯心主义的对立。

**** 物质是不依赖于意识又能为意识所反映的客观实在

**** 运动是物质的根本属性

**** 时间和空间是物质运动的存在方式

*** 实践的本质、特点、形式和作用

**** 实践是主体能动的改造和探索客体的客观物质活动

**** 人生活于其中的世界是与人的实践相联系的物质世界

*** 社会生活在本质上是实践的

** 物质世界的普遍联系和永恒发展

*** 联系与发展的普遍性和多样性

**** 世界联系的普遍性和多样性

**** 世界的运动发展

**** 两种对立的发展观

*** 世界联系与发展的基本规律

**** 对立统一规律

**** 质量互变规律

**** 否定之否定规律

*** 世界联系与发展的基本环节

**** 原因和结果

**** 必然性和偶然性

**** 可能性和现实性

**** 内容和形式

**** 本质和现象

** 客观规律性与主观能动性

*** 自然规律和社会规律

**** 规律和自然规律

**** 社会发展是有规律的自然历史过程

*** 意识及其能动作用

**** 意识的起源和本质

**** 意识的能动作用

**** 发挥主观能动性和尊重客观规律的关系
